spring:
  application:
    name: appi-log
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://appi-log-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.appsdeveloperblog: debug
  file:
    name: log.xml
    path: /logs